### ISSUE TITLE
Users created At is always updated on update query

### ISSUE THREAD

**Issue by MergHQ** [TKOaly/user-service#7]

**Comment by alehuo** [comment]
Possible fix should be implemented here: https://github.com/TKOaly/user-service/blob/f5a353685c4f823baae77dc4c4bd11b83e349723/src/services/UserService.ts#L203

As the user object gets created, createdAt gets assigned `this.createdAt || new Date();`. The property should be deleted using `delete newUser.createdAt` to make sure that createdAt doesn't get updated.

**Comment by alehuo** [comment]
Resolved
